/*
 * James Toetsweek 2.0 learning data.
 *
 * Add a subject by copying one subject object and filling:
 * meta, topics, flashcards and questions. The interface reads this file
 * automatically; no route or layout changes are needed.
 */
window.JAMES_DATA = {
  appName: "James Toetsweek",
  version: "2.0",
  schedule: [
    { day: "Maandag", subjectId: "frans" },
    { day: "Maandag", subjectId: "biologie" },
    { day: "Dinsdag", subjectId: "geschiedenis" },
    { day: "Woensdag", subjectId: "wiskunde" },
    { day: "Donderdag", subjectId: "engels" },
    { day: "Vrijdag", subjectId: "aardrijkskunde" },
  ],
  subjects: {
    biologie: {
      id: "biologie",
      name: "Biologie",
      short: "BIO",
      examDay: "Maandag",
      subtitle: "Thema 4 · Stevigheid en beweging",
      accent: "#35c987",
      enabled: true,
      quickTopicIds: ["skelet", "bouw-botten", "gewrichten", "spieren", "blessures", "rsi", "diagrammen"],
      topics: [
        {
          id: "skelet",
          title: "Functies van het skelet",
          summary: "Het skelet geeft stevigheid, beschermt organen en maakt samen met spieren beweging mogelijk.",
          points: [
            "Stevigheid: het skelet geeft je lichaam vorm en houdt je rechtop.",
            "Bescherming: schedel, ribben en wervelkolom beschermen kwetsbare organen.",
            "Beweging: botten, gewrichten en spieren werken samen als een bewegingsapparaat.",
          ],
        },
        {
          id: "bouw-botten",
          title: "Kalkstof en lijmstof",
          summary: "Kalkstof maakt bot hard; lijmstof maakt bot buigzaam. De verhouding verandert met je leeftijd.",
          points: [
            "Kalkstof zorgt voor hardheid en stevigheid.",
            "Lijmstof zorgt voor buigzaamheid.",
            "Kinderbotten bevatten relatief veel lijmstof; oudere botten relatief veel kalkstof en breken makkelijker.",
          ],
        },
        {
          id: "botten",
          title: "Belangrijke botten",
          summary: "Herken schedel, ribben, wervelkolom, bekken, dijbeen en scheenbeen in een diagram.",
          points: [
            "Schedel beschermt de hersenen; ribben beschermen hart en longen.",
            "De wervelkolom beschermt het ruggenmerg en draagt het bovenlichaam.",
            "Bekken, dijbeen en scheenbeen zijn belangrijke delen van het onderste skelet.",
          ],
        },
        {
          id: "gewrichten",
          title: "Gewrichten, pezen en banden",
          summary: "Een gewricht verbindt botten beweeglijk. Pezen verbinden spier met bot; banden verbinden bot met bot.",
          points: [
            "Scharniergewricht: vooral buigen en strekken, zoals knie en elleboog.",
            "Kogelgewricht: bewegen in veel richtingen, zoals schouder en heup.",
            "Kraakbeen en gewrichtssmeer verminderen wrijving en slijtage.",
          ],
        },
        {
          id: "spieren",
          title: "Biceps en triceps",
          summary: "Spieren kunnen alleen trekken. Daarom werken biceps en triceps als antagonisten.",
          points: [
            "Bij buigen trekt de biceps samen en ontspant de triceps.",
            "Bij strekken trekt de triceps samen en ontspant de biceps.",
            "Een spier die samentrekt wordt korter en dikker.",
          ],
        },
        {
          id: "blessures",
          title: "Blessures",
          summary: "Ken het verschil tussen botbreuk, kneuzing, verstuiking en ontwrichting.",
          points: [
            "Verstuiking: gewrichtsbanden rekken te ver of scheuren.",
            "Ontwrichting: gewrichtskop schiet uit de gewrichtskom.",
            "Warming-up, goede techniek en bescherming helpen blessures voorkomen.",
          ],
        },
        {
          id: "rsi",
          title: "RSI en houding",
          summary: "RSI ontstaat door langdurig dezelfde kleine bewegingen of een slechte werkhouding.",
          points: [
            "RSI betekent Repetitive Strain Injury.",
            "Wissel houding en werkzaamheden af en neem korte pauzes.",
            "Stel stoel, scherm en bureau goed af.",
          ],
        },
        {
          id: "diagrammen",
          title: "Diagrammen lezen",
          summary: "Lees eerst titel, assen, eenheden en legenda; trek pas daarna een conclusie.",
          points: [
            "De horizontale as is de x-as; de verticale as is de y-as.",
            "Controleer schaalverdeling en eenheid voordat je waarden afleest.",
            "Een conclusie beschrijft het zichtbare verband en verzint geen oorzaak.",
          ],
        },
      ],
      flashcards: [
        { id: "bio-f01", topicId: "skelet", front: "Noem de drie functies van het skelet.", back: "Stevigheid, bescherming en beweging.", difficulty: "easy", priority: true },
        { id: "bio-f02", topicId: "bouw-botten", front: "Wat doet kalkstof in bot?", back: "Kalkstof maakt bot hard en stevig.", difficulty: "easy", priority: true },
        { id: "bio-f03", topicId: "bouw-botten", front: "Wat doet lijmstof in bot?", back: "Lijmstof maakt bot buigzaam.", difficulty: "easy", priority: true },
        { id: "bio-f04", topicId: "botten", front: "Welk bot beschermt de hersenen?", back: "De schedel.", difficulty: "easy", priority: false },
        { id: "bio-f05", topicId: "botten", front: "Wat beschermen de ribben?", back: "Onder andere hart en longen.", difficulty: "easy", priority: false },
        { id: "bio-f06", topicId: "botten", front: "Welk bot zit in het bovenbeen?", back: "Het dijbeen.", difficulty: "easy", priority: false },
        { id: "bio-f07", topicId: "botten", front: "Welk bot zit voor in het onderbeen?", back: "Het scheenbeen.", difficulty: "medium", priority: false },
        { id: "bio-f08", topicId: "gewrichten", front: "Noem twee scharniergewrichten.", back: "Knie en elleboog.", difficulty: "easy", priority: true },
        { id: "bio-f09", topicId: "gewrichten", front: "Noem twee kogelgewrichten.", back: "Schouder en heup.", difficulty: "easy", priority: true },
        { id: "bio-f10", topicId: "gewrichten", front: "Wat verbindt een pees?", back: "Een spier met een bot.", difficulty: "easy", priority: true },
        { id: "bio-f11", topicId: "gewrichten", front: "Wat verbindt een band?", back: "Een bot met een ander bot.", difficulty: "easy", priority: true },
        { id: "bio-f12", topicId: "gewrichten", front: "Waarom zit kraakbeen op botuiteinden?", back: "Het vermindert wrijving en voorkomt slijtage.", difficulty: "medium", priority: false },
        { id: "bio-f13", topicId: "spieren", front: "Wat gebeurt er bij het buigen van je arm?", back: "Biceps trekt samen; triceps ontspant.", difficulty: "medium", priority: true },
        { id: "bio-f14", topicId: "spieren", front: "Wat gebeurt er bij het strekken van je arm?", back: "Triceps trekt samen; biceps ontspant.", difficulty: "medium", priority: true },
        { id: "bio-f15", topicId: "spieren", front: "Waarom werken spieren vaak in paren?", back: "Een spier kan alleen trekken, niet duwen.", difficulty: "hard", priority: false },
        { id: "bio-f16", topicId: "blessures", front: "Wat is een verstuiking?", back: "Gewrichtsbanden zijn te ver uitgerekt of gescheurd.", difficulty: "medium", priority: true },
        { id: "bio-f17", topicId: "blessures", front: "Wat is een ontwrichting?", back: "De gewrichtskop schiet uit de gewrichtskom.", difficulty: "medium", priority: true },
        { id: "bio-f18", topicId: "blessures", front: "Waarom doe je een warming-up?", back: "Om spieren en gewrichten voor te bereiden en blessures te helpen voorkomen.", difficulty: "medium", priority: false },
        { id: "bio-f19", topicId: "rsi", front: "Waar staat RSI voor?", back: "Repetitive Strain Injury.", difficulty: "easy", priority: true },
        { id: "bio-f20", topicId: "rsi", front: "Hoe verklein je de kans op RSI?", back: "Afwisselen, goed zitten en regelmatig korte pauzes nemen.", difficulty: "medium", priority: true },
        { id: "bio-f21", topicId: "diagrammen", front: "Wat controleer je eerst bij een diagram?", back: "Titel, assen, eenheden, legenda en schaal.", difficulty: "medium", priority: true },
        { id: "bio-f22", topicId: "diagrammen", front: "Welke as is meestal horizontaal?", back: "De x-as.", difficulty: "easy", priority: false },
        { id: "bio-f23", topicId: "diagrammen", front: "Wat is een goede diagramconclusie?", back: "Een beschrijving van het zichtbare verband, zonder een oorzaak te verzinnen.", difficulty: "hard", priority: true },
        { id: "bio-f24", topicId: "bouw-botten", front: "Waarom breken botten van ouderen makkelijker?", back: "Ze zijn relatief minder buigzaam en bevatten naar verhouding meer kalkstof.", difficulty: "hard", priority: false },
      ],
      questions: [
        { id: "bio-q01", topicId: "skelet", type: "mc", prompt: "Welke drie functies heeft het skelet?", options: ["Groei, ademhaling en vertering", "Stevigheid, bescherming en beweging", "Warmte, opslag en afweer", "Voelen, denken en reageren"], correctAnswer: 1, explanation: "Het skelet geeft vorm en stevigheid, beschermt organen en helpt bij beweging.", difficulty: "easy", priority: true },
        { id: "bio-q02", topicId: "skelet", type: "open", prompt: "Noem de drie functies van het skelet.", correctAnswer: "stevigheid, bescherming en beweging", requiredKeywords: ["stevigheid", "bescherming", "beweging"], explanation: "Alle drie zijn nodig voor een volledig antwoord.", difficulty: "medium", priority: true },
        { id: "bio-q03", topicId: "bouw-botten", type: "mc", prompt: "Welke stof maakt bot hard?", options: ["Lijmstof", "Kalkstof", "Gewrichtssmeer", "Kraakbeen"], correctAnswer: 1, explanation: "Kalkstof zorgt voor de hardheid van bot.", difficulty: "easy", priority: true },
        { id: "bio-q04", topicId: "bouw-botten", type: "open", prompt: "Welke stof maakt bot buigzaam?", correctAnswer: "lijmstof", acceptedAnswers: ["lijmstof"], explanation: "Lijmstof geeft bot elasticiteit en buigzaamheid.", difficulty: "easy", priority: true },
        { id: "bio-q05", topicId: "bouw-botten", type: "mc", prompt: "Waarom zijn kinderbotten relatief buigzaam?", options: ["Ze bevatten relatief veel lijmstof", "Ze bevatten geen kalkstof", "Ze bestaan alleen uit kraakbeen", "Ze bevatten extra gewrichtssmeer"], correctAnswer: 0, explanation: "Kinderbotten bevatten naar verhouding meer lijmstof.", difficulty: "medium", priority: false },
        { id: "bio-q06", topicId: "botten", type: "mc", prompt: "Welk bot beschermt de hersenen?", options: ["Bekken", "Schedel", "Dijbeen", "Wervelkolom"], correctAnswer: 1, explanation: "De schedel vormt een harde beschermlaag rond de hersenen.", difficulty: "easy", priority: false },
        { id: "bio-q07", topicId: "botten", type: "open", prompt: "Welk bot zit in het bovenbeen?", correctAnswer: "dijbeen", acceptedAnswers: ["dijbeen", "het dijbeen"], explanation: "Het dijbeen loopt van heup naar knie.", difficulty: "easy", priority: false },
        { id: "bio-q08", topicId: "botten", type: "mc", prompt: "Wat beschermen de ribben vooral?", options: ["Hersenen en ogen", "Hart en longen", "Maag en benen", "Ruggenmerg en hersenen"], correctAnswer: 1, explanation: "De ribben vormen de borstkas rond hart en longen.", difficulty: "easy", priority: false },
        { id: "bio-q09", topicId: "gewrichten", type: "mc", prompt: "Welke combinatie bevat twee scharniergewrichten?", options: ["Schouder en heup", "Knie en elleboog", "Heup en knie", "Schouder en elleboog"], correctAnswer: 1, explanation: "Knie en elleboog bewegen vooral als een scharnier.", difficulty: "easy", priority: true },
        { id: "bio-q10", topicId: "gewrichten", type: "open", prompt: "Noem één voorbeeld van een kogelgewricht.", correctAnswer: "schouder of heup", acceptedAnswers: ["schouder", "heup", "schoudergewricht", "heupgewricht"], explanation: "Schouder en heup kunnen in veel richtingen bewegen.", difficulty: "easy", priority: true },
        { id: "bio-q11", topicId: "gewrichten", type: "mc", prompt: "Wat verbindt een pees?", options: ["Bot met bot", "Spier met bot", "Spier met spier", "Kraakbeen met bot"], correctAnswer: 1, explanation: "Via een pees trekt een spier aan een bot.", difficulty: "easy", priority: true },
        { id: "bio-q12", topicId: "gewrichten", type: "open", prompt: "Wat verbindt een gewrichtsband?", correctAnswer: "bot met bot", requiredKeywords: ["bot", "bot"], acceptedAnswers: ["bot met bot", "een bot met een bot", "botten met elkaar"], explanation: "Banden houden botten bij een gewricht bij elkaar.", difficulty: "medium", priority: true },
        { id: "bio-q13", topicId: "gewrichten", type: "mc", prompt: "Wat is de functie van kraakbeen op botuiteinden?", options: ["Bot langer maken", "Wrijving en slijtage verminderen", "Spieren aan bot vastmaken", "Kalkstof opslaan"], correctAnswer: 1, explanation: "Kraakbeen vormt een glad en veerkrachtig laagje.", difficulty: "medium", priority: false },
        { id: "bio-q14", topicId: "spieren", type: "mc", prompt: "Welke spier trekt samen als je je arm buigt?", options: ["Triceps", "Biceps", "Kuitspier", "Buikspier"], correctAnswer: 1, explanation: "De biceps wordt korter en dikker tijdens het buigen.", difficulty: "easy", priority: true },
        { id: "bio-q15", topicId: "spieren", type: "open", prompt: "Welke spier trekt samen als je je arm strekt?", correctAnswer: "triceps", acceptedAnswers: ["triceps", "de triceps"], explanation: "Bij strekken trekt de triceps samen en ontspant de biceps.", difficulty: "easy", priority: true },
        { id: "bio-q16", topicId: "spieren", type: "mc", prompt: "Waarom werken biceps en triceps als antagonisten?", options: ["Ze trekken altijd tegelijk samen", "Spieren kunnen alleen trekken", "Ze zitten aan hetzelfde bot vast", "Ze maken kalkstof"], correctAnswer: 1, explanation: "Omdat spieren niet kunnen duwen is voor de tegengestelde beweging een andere spier nodig.", difficulty: "hard", priority: true },
        { id: "bio-q17", topicId: "spieren", type: "open", prompt: "Wat gebeurt er met een spier als hij samentrekt?", correctAnswer: "hij wordt korter en dikker", requiredKeywords: ["korter", "dikker"], explanation: "Een samentrekkende spier wordt korter én dikker.", difficulty: "medium", priority: false },
        { id: "bio-q18", topicId: "blessures", type: "mc", prompt: "Wat gebeurt er bij een verstuiking?", options: ["Een bot breekt", "Gewrichtsbanden rekken te ver of scheuren", "Een spier verdwijnt", "De huid raakt verbrand"], correctAnswer: 1, explanation: "Een verstuiking beschadigt de banden rond een gewricht.", difficulty: "medium", priority: true },
        { id: "bio-q19", topicId: "blessures", type: "open", prompt: "Hoe heet het als een gewrichtskop uit de kom schiet?", correctAnswer: "ontwrichting", acceptedAnswers: ["ontwrichting", "luxatie"], explanation: "Bij een ontwrichting passen kop en kom niet meer op hun plaats.", difficulty: "medium", priority: true },
        { id: "bio-q20", topicId: "blessures", type: "mc", prompt: "Welke actie helpt een sportblessure voorkomen?", options: ["Zonder voorbereiding maximaal sprinten", "Een warming-up doen", "Pijn negeren", "Altijd dezelfde beweging herhalen"], correctAnswer: 1, explanation: "Een warming-up bereidt spieren en gewrichten voor.", difficulty: "easy", priority: true },
        { id: "bio-q21", topicId: "blessures", type: "mc", prompt: "Wat is een botbreuk?", options: ["Een beschadiging van een gewrichtsband", "Een breuk of scheur in botweefsel", "Spierpijn na bewegen", "Slijtage van kraakbeen"], correctAnswer: 1, explanation: "Bij een botbreuk is het bot geheel of gedeeltelijk gebroken.", difficulty: "easy", priority: false },
        { id: "bio-q22", topicId: "rsi", type: "open", prompt: "Waar staat de afkorting RSI voor?", correctAnswer: "Repetitive Strain Injury", acceptedAnswers: ["repetitive strain injury"], explanation: "De naam verwijst naar overbelasting door herhaalde bewegingen.", difficulty: "medium", priority: true },
        { id: "bio-q23", topicId: "rsi", type: "mc", prompt: "Waardoor kan RSI ontstaan?", options: ["Door afwisselend bewegen", "Door langdurig dezelfde kleine bewegingen", "Door een korte warming-up", "Door voldoende pauzes"], correctAnswer: 1, explanation: "Herhaling en een slechte werkhouding kunnen spieren en pezen overbelasten.", difficulty: "easy", priority: true },
        { id: "bio-q24", topicId: "rsi", type: "open", prompt: "Noem één manier om RSI te helpen voorkomen.", correctAnswer: "afwisselen, goed zitten of pauzes nemen", acceptedAnswers: ["afwisselen", "pauze", "pauzes", "goede houding", "goed zitten", "werkhouding", "stoel goed afstellen", "scherm goed afstellen"], explanation: "Afwisseling, ergonomie en korte pauzes verminderen langdurige overbelasting.", difficulty: "medium", priority: true },
        { id: "bio-q25", topicId: "diagrammen", type: "mc", prompt: "Welke as is in een diagram meestal horizontaal?", options: ["De y-as", "De x-as", "De z-as", "De legenda-as"], correctAnswer: 1, explanation: "De x-as loopt horizontaal; de y-as verticaal.", difficulty: "easy", priority: true },
        { id: "bio-q26", topicId: "diagrammen", type: "open", prompt: "Noem twee dingen die je controleert voordat je een diagram afleest.", correctAnswer: "bijvoorbeeld titel, assen, eenheden, legenda of schaal", acceptedAnswers: ["titel en assen", "assen en eenheden", "titel en legenda", "schaal en eenheid", "legenda en schaal"], requiredAny: ["titel", "as", "assen", "eenheid", "eenheden", "legenda", "schaal"], minimumMatches: 2, explanation: "Controleer altijd de context en meeteenheden voordat je een waarde of verband noemt.", difficulty: "medium", priority: true },
        { id: "bio-q27", topicId: "diagrammen", type: "mc", prompt: "Wat hoort in een goede conclusie bij een diagram?", options: ["Alleen je eigen mening", "Het zichtbare verband in de gegevens", "Een oorzaak die niet is gemeten", "Alle losse getallen zonder verband"], correctAnswer: 1, explanation: "Een conclusie beschrijft wat de gegevens laten zien.", difficulty: "medium", priority: true },
        { id: "bio-q28", topicId: "diagrammen", type: "mc", prompt: "De y-as loopt van 0 tot 100 in stappen van 20. Welke waarde ligt na 60?", options: ["70", "80", "90", "100"], correctAnswer: 1, explanation: "De schaal gaat steeds met 20 omhoog: 0, 20, 40, 60, 80.", difficulty: "medium", priority: false },
        { id: "bio-q29", topicId: "bouw-botten", type: "mc", prompt: "Waarom breken botten van oudere mensen vaak makkelijker?", options: ["Ze bevatten relatief meer lijmstof", "Ze zijn vaak minder buigzaam", "Ze bevatten geen kalkstof", "Ze bestaan uit spieren"], correctAnswer: 1, explanation: "Met de leeftijd neemt de buigzaamheid af, waardoor botten brozer kunnen zijn.", difficulty: "hard", priority: false },
        { id: "bio-q30", topicId: "skelet", type: "open", prompt: "Hoe heten botten, gewrichten en spieren samen?", correctAnswer: "het bewegingsapparaat", acceptedAnswers: ["bewegingsapparaat", "het bewegingsapparaat"], explanation: "Deze onderdelen werken samen om houding en beweging mogelijk te maken.", difficulty: "hard", priority: false },
      ],
    },
    frans: {
      id: "frans",
      name: "Frans",
      short: "FR",
      examDay: "Maandag",
      subtitle: "Chapitre 5 · Entre Copains",
      accent: "#35c987",
      enabled: true,
      quickTopicIds: ["maanden", "familie", "uiterlijk", "activiteiten", "zinnen", "passe-compose"],
      topics: [
        {
          id: "maanden",
          title: "De maanden",
          summary: "Leer de twaalf maanden in de juiste volgorde en let op de Franse spelling.",
          points: [
            "janvier, février, mars, avril, mai, juin",
            "juillet, août, septembre, octobre, novembre, décembre",
            "Maanden krijgen in het Frans normaal geen hoofdletter.",
          ],
        },
        {
          id: "familie",
          title: "Familie",
          summary: "Gebruik mon/ma/mes en ken de belangrijkste familieleden.",
          points: [
            "père, mère, frère, sœur",
            "grand-père, grand-mère, oncle, tante, cousin, cousine",
            "mon voor mannelijk, ma voor vrouwelijk en mes voor meervoud.",
          ],
        },
        {
          id: "uiterlijk",
          title: "Uiterlijk beschrijven",
          summary: "Gebruik être voor algemene kenmerken en avoir voor haar en ogen.",
          points: [
            "Il est grand / Elle est grande.",
            "Il a les cheveux noirs et les yeux bleus.",
            "petit/petite, français/française en kleuren zoals bleu, vert en noir.",
          ],
        },
        {
          id: "activiteiten",
          title: "Activiteiten",
          summary: "Herken en gebruik veelvoorkomende activiteiten met jouer, faire, regarder en écouter.",
          points: [
            "jouer au football, faire du vélo, danser, chanter",
            "regarder un film, écouter de la musique",
            "organiser une fête, inviter des amis, rigoler",
          ],
        },
        {
          id: "zinnen",
          title: "Belangrijke zinnen",
          summary: "Kernzinnen helpen bij vertellen, vragen stellen en afspreken.",
          points: [
            "Comment tu t'appelles ? Je m'appelle James.",
            "Qu'est-ce que tu aimes faire ? J'aime jouer au football.",
            "Tu veux venir ? Oui, avec plaisir ! / Désolé, je ne peux pas.",
          ],
        },
        {
          id: "passe-compose",
          title: "Passé composé",
          summary: "Voor deze stof: onderwerp + vorm van avoir + voltooid deelwoord.",
          points: [
            "j'ai, tu as, il/elle a, nous avons, vous avez, ils/elles ont",
            "Regelmatige werkwoorden op -er krijgen meestal -é.",
            "joué, regardé, mangé, parlé, invité, organisé, acheté, dansé, chanté, rigolé",
          ],
        },
        {
          id: "getallen",
          title: "Getallen",
          summary: "Herhaal vooral de lastige tientallen en samenstellingen.",
          points: [
            "70 soixante-dix; 72 soixante-douze; 75 soixante-quinze",
            "81 quatre-vingt-un; 92 quatre-vingt-douze",
            "100 cent",
          ],
        },
      ],
      flashcards: [
        { id: "fra-f01", topicId: "maanden", front: "januari", back: "janvier", difficulty: "easy", priority: true },
        { id: "fra-f02", topicId: "maanden", front: "februari", back: "février", difficulty: "medium", priority: true },
        { id: "fra-f03", topicId: "maanden", front: "juni", back: "juin", difficulty: "medium", priority: true },
        { id: "fra-f04", topicId: "maanden", front: "juli", back: "juillet", difficulty: "medium", priority: true },
        { id: "fra-f05", topicId: "maanden", front: "augustus", back: "août", difficulty: "hard", priority: true },
        { id: "fra-f06", topicId: "maanden", front: "december", back: "décembre", difficulty: "medium", priority: true },
        { id: "fra-f07", topicId: "familie", front: "mijn vader", back: "mon père", difficulty: "easy", priority: true },
        { id: "fra-f08", topicId: "familie", front: "mijn moeder", back: "ma mère", difficulty: "easy", priority: true },
        { id: "fra-f09", topicId: "familie", front: "mijn zus", back: "ma sœur", difficulty: "medium", priority: true },
        { id: "fra-f10", topicId: "familie", front: "mijn grootouders", back: "mes grands-parents", difficulty: "hard", priority: false },
        { id: "fra-f11", topicId: "uiterlijk", front: "Hij is groot.", back: "Il est grand.", difficulty: "easy", priority: true },
        { id: "fra-f12", topicId: "uiterlijk", front: "Zij is klein.", back: "Elle est petite.", difficulty: "easy", priority: true },
        { id: "fra-f13", topicId: "uiterlijk", front: "Hij heeft blauwe ogen.", back: "Il a les yeux bleus.", difficulty: "medium", priority: true },
        { id: "fra-f14", topicId: "activiteiten", front: "voetballen", back: "jouer au football", difficulty: "easy", priority: true },
        { id: "fra-f15", topicId: "activiteiten", front: "naar muziek luisteren", back: "écouter de la musique", difficulty: "medium", priority: true },
        { id: "fra-f16", topicId: "activiteiten", front: "een feest organiseren", back: "organiser une fête", difficulty: "medium", priority: false },
        { id: "fra-f17", topicId: "zinnen", front: "Hoe heet je?", back: "Comment tu t'appelles ?", difficulty: "medium", priority: true },
        { id: "fra-f18", topicId: "zinnen", front: "Ik heet James.", back: "Je m'appelle James.", difficulty: "easy", priority: true },
        { id: "fra-f19", topicId: "zinnen", front: "Wil je komen?", back: "Tu veux venir ?", difficulty: "medium", priority: true },
        { id: "fra-f20", topicId: "passe-compose", front: "Hoe maak je hier de passé composé?", back: "Onderwerp + avoir + voltooid deelwoord.", difficulty: "medium", priority: true },
        { id: "fra-f21", topicId: "passe-compose", front: "Voltooid deelwoord van jouer", back: "joué", difficulty: "easy", priority: true },
        { id: "fra-f22", topicId: "passe-compose", front: "Voltooid deelwoord van acheter", back: "acheté", difficulty: "medium", priority: true },
        { id: "fra-f23", topicId: "getallen", front: "92", back: "quatre-vingt-douze", difficulty: "hard", priority: false },
        { id: "fra-f24", topicId: "getallen", front: "75", back: "soixante-quinze", difficulty: "medium", priority: false },
      ],
      questions: [
        { id: "fra-q01", topicId: "maanden", type: "mc", prompt: "Wat is januari in het Frans?", options: ["juin", "janvier", "juillet", "février"], correctAnswer: 1, explanation: "Januari is janvier.", difficulty: "easy", priority: true },
        { id: "fra-q02", topicId: "maanden", type: "open", prompt: "Vertaal: februari", correctAnswer: "février", acceptedAnswers: ["février", "fevrier"], explanation: "De correcte spelling is février, met accenten.", difficulty: "medium", priority: true },
        { id: "fra-q03", topicId: "maanden", type: "mc", prompt: "Welke maand komt na juin?", options: ["juillet", "mai", "août", "janvier"], correctAnswer: 0, explanation: "Na juni (juin) komt juli (juillet).", difficulty: "medium", priority: true },
        { id: "fra-q04", topicId: "maanden", type: "open", prompt: "Vertaal: augustus", correctAnswer: "août", acceptedAnswers: ["août", "aout"], explanation: "Augustus is août.", difficulty: "hard", priority: true },
        { id: "fra-q05", topicId: "maanden", type: "mc", prompt: "Wat is december in het Frans?", options: ["novembre", "décembre", "septembre", "octobre"], correctAnswer: 1, explanation: "December is décembre.", difficulty: "easy", priority: true },
        { id: "fra-q06", topicId: "maanden", type: "open", prompt: "Vertaal: september", correctAnswer: "septembre", acceptedAnswers: ["septembre"], explanation: "September is septembre.", difficulty: "easy", priority: false },
        { id: "fra-q07", topicId: "familie", type: "mc", prompt: "Hoe zeg je 'mijn vader'?", options: ["ma père", "mon père", "mes père", "mon frère"], correctAnswer: 1, explanation: "Père is mannelijk, dus je gebruikt mon.", difficulty: "easy", priority: true },
        { id: "fra-q08", topicId: "familie", type: "open", prompt: "Vertaal: mijn moeder", correctAnswer: "ma mère", acceptedAnswers: ["ma mère", "ma mere"], explanation: "Mère is vrouwelijk, dus je gebruikt ma.", difficulty: "easy", priority: true },
        { id: "fra-q09", topicId: "familie", type: "mc", prompt: "Wat betekent 'ma sœur'?", options: ["mijn moeder", "mijn zus", "mijn tante", "mijn nicht"], correctAnswer: 1, explanation: "Sœur betekent zus.", difficulty: "easy", priority: true },
        { id: "fra-q10", topicId: "familie", type: "open", prompt: "Vertaal: mijn broer", correctAnswer: "mon frère", acceptedAnswers: ["mon frère", "mon frere"], explanation: "Frère is mannelijk: mon frère.", difficulty: "medium", priority: false },
        { id: "fra-q11", topicId: "familie", type: "mc", prompt: "Wanneer gebruik je 'mes'?", options: ["Voor mannelijk enkelvoud", "Voor vrouwelijk enkelvoud", "Voor meervoud", "Alleen voor ouders"], correctAnswer: 2, explanation: "Mes gebruik je voor meerdere personen of dingen.", difficulty: "medium", priority: true },
        { id: "fra-q12", topicId: "uiterlijk", type: "mc", prompt: "Welke zin betekent 'Zij is groot'?", options: ["Elle est grand", "Elle est grande", "Il est grande", "Elle a grande"], correctAnswer: 1, explanation: "Bij vrouwelijk enkelvoud krijgt grand een e: grande.", difficulty: "medium", priority: true },
        { id: "fra-q13", topicId: "uiterlijk", type: "open", prompt: "Vertaal: Hij heeft blauwe ogen.", correctAnswer: "Il a les yeux bleus.", acceptedAnswers: ["il a les yeux bleus", "il a des yeux bleus"], explanation: "Voor ogen gebruik je avoir: il a les yeux bleus.", difficulty: "hard", priority: true },
        { id: "fra-q14", topicId: "uiterlijk", type: "mc", prompt: "Wat is de vrouwelijke vorm van petit?", options: ["petits", "petite", "petites", "petitée"], correctAnswer: 1, explanation: "Vrouwelijk enkelvoud is petite.", difficulty: "easy", priority: true },
        { id: "fra-q15", topicId: "uiterlijk", type: "open", prompt: "Wat is de vrouwelijke vorm van français?", correctAnswer: "française", acceptedAnswers: ["française", "francaise"], explanation: "De vrouwelijke vorm is française.", difficulty: "medium", priority: false },
        { id: "fra-q16", topicId: "uiterlijk", type: "mc", prompt: "Welke rij bevat alleen kleuren uit de basisstof?", options: ["bleu, vert, noir", "grand, petit, noir", "père, vert, bleu", "joué, noir, petite"], correctAnswer: 0, explanation: "Bleu, vert en noir zijn alle drie kleuren.", difficulty: "easy", priority: false },
        { id: "fra-q17", topicId: "activiteiten", type: "mc", prompt: "Hoe zeg je 'voetballen'?", options: ["faire le football", "jouer au football", "regarder football", "écouter au football"], correctAnswer: 1, explanation: "Bij een sport gebruik je hier jouer au.", difficulty: "easy", priority: true },
        { id: "fra-q18", topicId: "activiteiten", type: "open", prompt: "Vertaal: naar muziek luisteren", correctAnswer: "écouter de la musique", acceptedAnswers: ["écouter de la musique", "ecouter de la musique"], explanation: "Écouter betekent luisteren naar.", difficulty: "medium", priority: true },
        { id: "fra-q19", topicId: "activiteiten", type: "mc", prompt: "Wat betekent 'regarder un film'?", options: ["Een film maken", "Een film kijken", "Een film kopen", "Over een film praten"], correctAnswer: 1, explanation: "Regarder betekent kijken.", difficulty: "easy", priority: true },
        { id: "fra-q20", topicId: "activiteiten", type: "open", prompt: "Vertaal: een feest organiseren", correctAnswer: "organiser une fête", acceptedAnswers: ["organiser une fête", "organiser une fete"], explanation: "Een feest is une fête.", difficulty: "hard", priority: false },
        { id: "fra-q21", topicId: "zinnen", type: "mc", prompt: "Wat betekent 'Comment tu t'appelles ?'?", options: ["Hoe gaat het?", "Hoe heet je?", "Waar woon je?", "Wat doe je?"], correctAnswer: 1, explanation: "Met deze vraag vraag je naar iemands naam.", difficulty: "easy", priority: true },
        { id: "fra-q22", topicId: "zinnen", type: "open", prompt: "Vertaal: Ik heet James.", correctAnswer: "Je m'appelle James.", acceptedAnswers: ["je m'appelle james", "je m appelle james"], explanation: "Je m'appelle betekent letterlijk: ik noem mezelf.", difficulty: "medium", priority: true },
        { id: "fra-q23", topicId: "zinnen", type: "mc", prompt: "Hoe vraag je 'Wil je komen?'", options: ["Tu veux venir ?", "Tu peux parler ?", "Tu aimes faire ?", "Tu vas où ?"], correctAnswer: 0, explanation: "Tu veux venir ? betekent: wil je komen?", difficulty: "medium", priority: true },
        { id: "fra-q24", topicId: "zinnen", type: "open", prompt: "Hoe zeg je: Ja, graag!", correctAnswer: "Oui, avec plaisir !", acceptedAnswers: ["oui avec plaisir", "oui, avec plaisir"], explanation: "Avec plaisir betekent met plezier/graag.", difficulty: "hard", priority: true },
        { id: "fra-q25", topicId: "passe-compose", type: "mc", prompt: "Hoe maak je in deze stof de passé composé?", options: ["être + infinitief", "avoir + voltooid deelwoord", "aller + infinitief", "avoir + tegenwoordige tijd"], correctAnswer: 1, explanation: "Gebruik een vorm van avoir gevolgd door het voltooid deelwoord.", difficulty: "easy", priority: true },
        { id: "fra-q26", topicId: "passe-compose", type: "open", prompt: "Wat is het voltooid deelwoord van jouer?", correctAnswer: "joué", acceptedAnswers: ["joué", "joue"], explanation: "Bij regelmatige -er-werkwoorden vervang je -er meestal door -é.", difficulty: "easy", priority: true },
        { id: "fra-q27", topicId: "passe-compose", type: "mc", prompt: "Welke zin betekent 'Ik heb gedanst'?", options: ["Je danse", "J'ai dansé", "Je suis danser", "J'ai danse"], correctAnswer: 1, explanation: "J'ai is de vorm van avoir; dansé is het voltooid deelwoord.", difficulty: "medium", priority: true },
        { id: "fra-q28", topicId: "passe-compose", type: "open", prompt: "Maak af: Nous ... regardé un film.", correctAnswer: "avons", acceptedAnswers: ["avons", "nous avons"], explanation: "Bij nous hoort de vorm avons.", difficulty: "medium", priority: true },
        { id: "fra-q29", topicId: "passe-compose", type: "mc", prompt: "Wat is het voltooid deelwoord van acheter?", options: ["acheter", "acheté", "achet", "achète"], correctAnswer: 1, explanation: "Acheter wordt acheté.", difficulty: "medium", priority: true },
        { id: "fra-q30", topicId: "getallen", type: "open", prompt: "Schrijf 92 in het Frans.", correctAnswer: "quatre-vingt-douze", acceptedAnswers: ["quatre-vingt-douze", "quatre vingt douze"], explanation: "92 is quatre-vingt-douze.", difficulty: "hard", priority: false },
      ],
    },
    geschiedenis: {
      id: "geschiedenis",
      name: "Geschiedenis",
      short: "GS",
      examDay: "Dinsdag",
      subtitle: "6.1, 6.2 en 6.5 · Nederlandse Opstand",
      accent: "#e1a44a",
      enabled: false,
      quickTopicIds: [],
      topics: [
        {
          id: "tijdlijn",
          title: "Tijdlijn",
          summary: "Maak een tijdlijn met gebeurtenissen, personen en oorzaken.",
          points: ["Koppel oorzaak en gevolg.", "Zet gebeurtenissen in chronologische volgorde."],
        },
      ],
      flashcards: [],
      questions: [],
    },
    wiskunde: {
      id: "wiskunde",
      name: "Wiskunde",
      short: "WI",
      examDay: "Woensdag",
      subtitle: "Hoofdstuk 8 · Formules",
      accent: "#5da9e9",
      enabled: false,
      quickTopicIds: [],
      topics: [
        {
          id: "formules",
          title: "Formules",
          summary: "Invullen, ombouwen, grafieken lezen en antwoorden controleren.",
          points: ["Schrijf tussenstappen op.", "Controleer eenheden en uitkomst."],
        },
      ],
      flashcards: [],
      questions: [],
    },
    engels: {
      id: "engels",
      name: "Engels",
      short: "EN",
      examDay: "Donderdag",
      subtitle: "Leesvaardigheid",
      accent: "#8d8cf0",
      enabled: false,
      quickTopicIds: [],
      topics: [
        {
          id: "lezen",
          title: "Leesstrategie",
          summary: "Lees vragen, scan de tekst, markeer sleutelwoorden en controleer.",
          points: ["Zoek gericht.", "Lees rondom het sleutelwoord."],
        },
      ],
      flashcards: [],
      questions: [],
    },
    aardrijkskunde: {
      id: "aardrijkskunde",
      name: "Aardrijkskunde",
      short: "AK",
      examDay: "Vrijdag",
      subtitle: "H4 · Natuurrampen in Japan",
      accent: "#f08057",
      enabled: false,
      quickTopicIds: [],
      topics: [
        {
          id: "rampen",
          title: "Natuurrampen",
          summary: "Aardbevingen, tsunami's, vulkanen, gevolgen en preventie.",
          points: ["Leg processen uit.", "Koppel risico aan preventie."],
        },
      ],
      flashcards: [],
      questions: [],
    },
  },
};
